### ISSUE TITLE
Activity & kube 1.25/cert-manger 1.10 status?

### ISSUE THREAD

**Issue by Jackbennett** [bwolf/cert-manager-webhook-gandi#24] opened 2022-11-10 15:39 UTC
I'm trying to make heads or tails of the logs on the webhook pod but to me this doesn't work anymore?

My certificates sit in "pending" waiting for ACME to see DNS records but I can't see the webhook even attempting to try gandi's api.

**Comment by bwolf** [comment] 2023-11-29 21:47
I cannot comment on this, because I no longer use this package. Since nobody else commented on this, I'm closing this issue, because I assume you either gave up, or found a fix and note reported back (here).

**Closed as completed by bwolf** 2023-11-29 21:47 UTC

**Comment by Jackbennett** [comment] 2023-11-29 22:45
Well that's a trip down memory lane. I swapped DNS over to digitalocean and used another cert-manager config.

I know there's a config I added to my dnsmasq in this network to specifically forward _acme challenges out to a public resolver. But I cannot recall if that came from this issue.

**Comment by bwolf** [comment] 2023-11-29 22:54
In the original README I setup the DNS resolver for cert-manager explicitly to use Google DNS (any other should work too) because I also had issues and the idea was not to rely on any defaults which could prevent reproducibility.

**Comment by Jackbennett** [comment] 2023-11-30 10:18
I found a lot of the gandi api and ecosystem did not work when using things owned by an organization rather than a user. So I moved to DigitalOcean for the API not resolvers.
